language: python
script: pytest
os: linux

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # Build and install package
    #- python setup.py develop --no-deps
  - pip install -e .
    # Print details of the environment
  - conda list
  - pip freeze

notifications:
    email: false

stages:
  - lint
  - test

  - deploy

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: "Check formatting of code for PEP-8"
      os: linux

      language: generic
      env: PYTHON_VER=3.8
      script:
        - flake8 control_parameters_step tests
        - yapf --diff --recursive  control_parameters_step tests

    - stage: test
      name: "Tests on MacOS Python 3.7"
      script:
        - pytest -v tests/
      os: osx
      language: generic
      env: PYTHON_VER=3.7

    - stage: test
      name: "Tests on MacOS Python 3.8"
      script:
        - pytest -v tests/
      os: osx
      language: generic
      env: PYTHON_VER=3.8

    - stage: test
      name: "Tests on Linux Python 3.7"
      script:
        - pytest -v tests/
      os: linux

      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.7

    - stage: test
      name: "Tests and coverage on Linux Python 3.8"
      script:
        - pytest -v --cov=control_parameters_step tests/
      after_success:
        - codecov
      os: linux

      language: generic
      env: PYTHON_VER=3.8


    - stage: deploy
      name: "Deploy to PyPi"
      if: tag IS present
      dist: xenial
      os: linux
      python: 3.8
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        skip_existing: true
        on:
          condition: $PYTHON_VER = 3.8
          condition: $TRAVIS_OS_NAME = linux
          repo: molssi-seamm/control_parameters_step
          tags: true
        username: seamm
        password:
          secure: JxTwiBYclNV3+j31O4iN2WPVvJ742ULQ53KW+tq2E3GqkVjYQ5U6duhZm87WUQ0bdy8Tpd6NAw3tx5nKXTUw6CAKmsruy9d0LIj9bmcDVV+te15LWw/8gUFEbdGa3041VnhBFfY1Azuu56wKK+YIZ8n+bzekEGCYYhczAYgEhgX0xuSKekao3CAqdwrAFOO2jm7WMm21U/U1esQeRqxxmytBqnwpZKWzkmIAC2iTtuHpcAVA3nhW/FBPUIK9uf4n3Kf9eQz/2z/B8bCK1X3F9bpNN13596kQx7m/uGPLLfl32gujoP1GiGS8phgSmiThYB3N2J9SbThGiq/wqbgBZTCZGOmR4BZvb0im5U37BOEctlLmrLoPQM5ZLlgOeZI3xMPIaFZE59RN2pl/rDlRsVLADgzMTXldgdqf+1yABy8poEb+9ILMr4C4KsBThgcNQIlFAJl3QllNHv5apy/OxXicdDKlw0M5I2Gv6cgJTdZuK1KGRARa25vSRMhKh6v1Q1yHZvI0UTRnV3XYsRLm4DBlIPO7BEOHXyZ1wjAXztjPcTidwB38OgsA3YnoFmdEnePLjksSfb3SCPJ9uBECFPmOdyqSHWLfsHjkhEidGvXR7aZT4nZFxt8qHKHGCWjo8Q+InO5G3irGmOtvDt13+ab6BE7IvbUMO74y5dWOoME=
